### PR TITLE
docs: added the readme file

### PR DESCRIPTION
**Pull request by pradipgharge**
Here's the preview : https://github.com/pradipgharge/Furnbuy/tree/README-file

### CODE REVIEW

**Review by Ankur9669 — APPROVED** [review]
Looking good

**Comment by anasm11** [comment]
The description looks very good. Looks good to merge.

**Review by mehulsatardekar — APPROVED** [review]
Looks good to merge

**Review by Sahil25061999 — APPROVED** [review]
Looks good, great use of emojis and gifs. Nice to see that you have described the content of each page, can be merged.

**Pull request merged**
